title: C++ Graphiti Rewrite
type: initiative
status: not_ready
slug: 9e79ec
log:
  - ts: 2026-03-08T13:20:06Z
    owner: unknown
    action: created
  - ts: 2026-03-08T13:20:06Z
    owner: unknown
    action: created