target("graphiti")
    set_kind("static")
    add_files("src/**.cpp")
    remove_files("src/server/**.cpp")
    remove_files("src/logger/**.cpp")
    add_includedirs("include", {public = true})
    add_headerfiles("include/(**.h)")
    add_includedirs("src", {private = true})
    add_deps("graphiti-core")
    add_deps("graphiti-kuzu")
    add_deps("graphiti-kuzu-writer")
    add_packages("kuzu", {public = true})
    add_packages("nlohmann_json", {public = true})
    add_packages("cpp-httplib")
    add_packages("openssl3")
    add_packages("yaml-cpp")
    add_packages("ixwebsocket", {public = true})
    if is_plat("windows") then
        add_syslinks("bcrypt")
    end
