title: "Phase 4: Pluggable Providers"
type: epic
status: not_ready
parent: 9e79ec
slug: 27b35a
log:
  - ts: 2026-03-08T13:20:12Z
    owner: unknown
    action: created
  - ts: 2026-03-08T13:20:12Z
    owner: unknown
    action: created