title: "Phase 1: MVP (add_episode + search)"
type: epic
status: not_ready
parent: 9e79ec
slug: 8ddf25
log:
  - ts: 2026-03-08T13:20:10Z
    owner: unknown
    action: created
  - ts: 2026-03-08T13:20:10Z
    owner: unknown
    action: created